# Generated by Django 3.1.1 on 2020-09-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('uuid', models.ManyToManyField(to='stuff.UuId', verbose_name='uuids')),
            ],
        ),
    ]
