# Generated by Django 3.1.1 on 2020-09-04 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_formulary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveSmallIntegerField(choices=[(0, 'Formulario de Inscripción'), (1, 'Evaluación Diagnóstica'), (2, 'Temario'), (3, 'Contrato de Adheción'), (4, 'Carta Bienvenida')], default=0)),
                ('url', models.URLField()),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuff.uuid')),
            ],
        ),
    ]
