# Generated by Django 3.1.1 on 2020-09-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_contentlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uuid',
            old_name='name',
            new_name='uuid',
        ),
    ]
